# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: npm cache clean --force
  displayName: 'Clean npm cache'

- script: npm install -g npm@latest
  displayName: 'Update npm'


- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'Install Angular CLI and Dependencies'

- script: |
    ng build --configuration=production && gzipper c ./dist/ --include js,css,html,ttf,woff2,woff,txt,svg,json,png,jpg,jpeg,gif,scss,eot,ico,xml,application/xml,application --output-file-format [filename].[ext] ./dist-new/
       
  displayName: 'Build Angular Application'

- script: |
   pwd $(Build.ArtifactStagingDirectory)
   ls

- script: |   
   pwd $(System.DefaultWorkingDirectory)
   ls

- task: CopyFiles@2
  inputs:
    contents: 'dist/**'
    targetFolder: '$(Build.ArtifactStagingDirectory)/dist'
  displayName: 'Copy Files to Artifact Staging Directory'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/dist'
    ArtifactName: 'dist'
  displayName: 'Publish Build Artifacts'

