version: 0.2
env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "angular-example-statics"
    BUILD_FOLDER: "angular-example-artifacts"
    BUILD_ENV: "prod"
phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build --${BUILD_ENV}
  post_build:
    commands:
      - aws s3 cp dist s3://${S3_BUCKET} --recursive
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
  discard-paths: yes
