version: 0.2
env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "angular-example-statics"
    BUILD_FOLDER: "angular-example-artifacts"
    BUILD_ENV: "prod"
phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - export filename="extension-v-$(cat manifest-prod.json | sed 's/.*\"version\"\: \"\(.*\)\".*/\1/;t;d')-prod.zip"
      - aws s3 cp $filename s3://${S3_BUCKET}
      - curl -X POST -H 'Content-type: application/json' --data '{"text":"<@Alexander Ivanov> http://${S3_BUCKET}/$filename"}' ${webhookURL}
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
  discard-paths: yes
